name: 'Snowflake'
version: '1.0'
config-version: 2
profile: 'default'
vars:
  surrogate_key_treat_nulls_as_empty_strings: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  Snowflake:
    +database: zurich
    +schema: agmt
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: mart
