name: 'Snowflake'
version: '1.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  Snowflake:
    +database: zurich
    +schema: atomic_cml_agmt
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: mart
