with src as (
  select 
    row_number() over (order by canonical_pol_nbr, norm_pol_eff_dt) as cml_agmt_id,
    {{ dbt_utils.surrogate_key(['POL_NBR', 'POL_EFF_DT']) }} as agmt_anchr_id,
    canonical_pol_nbr as pol_nbr,
    norm_pol_eff_dt as pol_eff_dt,
    TYP_ID,
    'N' as actv_rec_ind,
    inmy_agmt_anchr_id,
    ACQN_CD,
    ADT_FREQ_CD,
    UNBNDL_IND as bndl_cd,
    norm_pol_can_dt as can_dt,
    CAN_RSN_CD,
    'Y' ciid_match_ind,
    GEN_CUST_ID as cms_pty_id,
    CPAN_IND,
    CUST_NBR,
    null as dac_cd,
    PAR_CD as divd_par_cd,
    EXC_CD,
    INSTL_CD,
    POL_MODU_NBR as modu_nbr,
    MP_CD,
    norm_pol_expi_dt as plnd_end_dt,
    POL_CONTR_TYP_CD,
    POL_SYM as pol_sym_cd,
    null as port_ind,
    INSD_NM as pri_nmd_insd_nm,
    PRCG_OFC,
    PRDR_SRC_CD,
    RATG_ORI_CD,
    REINS_IND as reins_waqs_trty_cd,
    NEW_RENL_CD as renl_ind,
    RETRO_RTG_CD as retro_ratg_cd,
    RSK_TYP_CD,
    SIR_IND as self_insd_retn_ind,
    SIC_CD,
    CONTRACT_NBR_CML as src_pol_nbr,
    POL_EFF_DT as src_pol_eff_dt,
    LKP_SRC_POL_SYM_CD as src_pol_sym_cd,
    POL_CONTR_STS_CD as sts_cd,
    UNDG_PGM_CD,
    V_INV_POOL_FLAG as v_inv_pool_ind,
    current_timestamp() as eff_fm_tistmp,
    dateadd(year, 10, current_timestamp()) as eff_to_tistmp,
    POP_INFO_ID,
    POP_INFO_ID as updt_pop_info_id,
    BAT_ID,
    BIL_TYP_CD,
    INCP_DT,
    TERMS_IN_MONTHS as agmt_term_in_mnth,
    CONTR_TYPE_CD,
    MKT_CD,
    PERF_PROT_IND,
    SALE_DT,
    MKT_PRD_SPEC_ID,
    PYMT_PLN_CD,
    MSTR_POL_NBR,
    TAIL_EXPI_DT,
    LKP_POLHLDR_ENTPRS_ID as polhldr_entprs_id,
    LKP_POLHLDR_SITE_DUNS_NBR as polhldr_site_duns_nbr,
    PARNT_CHILD_CONTR_TYP_CD,
    PRI_NMD_INSD_FEIN_NBR,
    RATG_BAS_CD,
    ASSM_PTNR_CTRY_POL_ID,
    ASSM_US_POL_NBR,
    CEDE_PTNR_CTRY_ANCHR_ID,
    DRVD_CONTR_CRCY_CD,
    FRNT_CD,
    NON_RENL_RSN_CD,
    ZI_POL_SYS_CONTR_ID,
    GENL_LN_OF_BUSN_CD,
    CROP_INS_TYP_NBR,
    CROP_REINS_YY,
    DRVD_SNDBL_TO_GVMNT_IND,
    POL_PRCG_HLD_RSN_CD,
    POL_PRCG_STS_CD,
    SRC_CO_CD,
    SRC_SYS_CD,
    FRGN_PRDR_CD,
    DOWC_IND,
    AGE_BASE_RATG_BAS_CD,
    PLN_SPEC_CD
  from {{ ref('stg_billing_type_logic') }}
  where /* Update path criteria */ join_flag in ('A_AND_B', 'B_ONLY') and to_varchar(NVL(update_flag, 'Y')) = 'Y'
)
select * from src